// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: pingpong.proto
#ifndef GRPC_pingpong_2eproto__INCLUDED
#define GRPC_pingpong_2eproto__INCLUDED

#include "pingpong.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace pingpong {

class handl final {
 public:
  static constexpr char const* service_full_name() {
    return "pingpong.handl";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status pingpong(::grpc::ClientContext* context, const ::pingpong::ping& request, ::pingpong::pong* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pingpong::pong>> Asyncpingpong(::grpc::ClientContext* context, const ::pingpong::ping& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pingpong::pong>>(AsyncpingpongRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pingpong::pong>> PrepareAsyncpingpong(::grpc::ClientContext* context, const ::pingpong::ping& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pingpong::pong>>(PrepareAsyncpingpongRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pingpong::pong>* AsyncpingpongRaw(::grpc::ClientContext* context, const ::pingpong::ping& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pingpong::pong>* PrepareAsyncpingpongRaw(::grpc::ClientContext* context, const ::pingpong::ping& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status pingpong(::grpc::ClientContext* context, const ::pingpong::ping& request, ::pingpong::pong* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pingpong::pong>> Asyncpingpong(::grpc::ClientContext* context, const ::pingpong::ping& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pingpong::pong>>(AsyncpingpongRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pingpong::pong>> PrepareAsyncpingpong(::grpc::ClientContext* context, const ::pingpong::ping& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pingpong::pong>>(PrepareAsyncpingpongRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::pingpong::pong>* AsyncpingpongRaw(::grpc::ClientContext* context, const ::pingpong::ping& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pingpong::pong>* PrepareAsyncpingpongRaw(::grpc::ClientContext* context, const ::pingpong::ping& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_pingpong_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status pingpong(::grpc::ServerContext* context, const ::pingpong::ping* request, ::pingpong::pong* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_pingpong : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_pingpong() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_pingpong() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status pingpong(::grpc::ServerContext* context, const ::pingpong::ping* request, ::pingpong::pong* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestpingpong(::grpc::ServerContext* context, ::pingpong::ping* request, ::grpc::ServerAsyncResponseWriter< ::pingpong::pong>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_pingpong<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_pingpong : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_pingpong() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_pingpong() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status pingpong(::grpc::ServerContext* context, const ::pingpong::ping* request, ::pingpong::pong* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_pingpong : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_pingpong() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::pingpong::ping, ::pingpong::pong>(std::bind(&WithStreamedUnaryMethod_pingpong<BaseClass>::Streamedpingpong, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_pingpong() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status pingpong(::grpc::ServerContext* context, const ::pingpong::ping* request, ::pingpong::pong* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedpingpong(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::pingpong::ping,::pingpong::pong>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_pingpong<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_pingpong<Service > StreamedService;
};

}  // namespace pingpong


#endif  // GRPC_pingpong_2eproto__INCLUDED
